name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Construção do projeto com Maven, incluindo o Maven Shade Plugin
      - name: Build with Maven
        run: |
          mvn -f sustentaree/pom.xml clean install -DskipTests

      # Upload de todos os artefatos gerados na pasta target
      - name: Upload all JARs and target contents
        uses: actions/upload-artifact@v4
        with:
          name: sustentaree-target
          path: sustentaree/target/*

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      # Baixar todos os artefatos gerados no job anterior
      - name: Download JAR artifacts
        uses: actions/download-artifact@v4
        with:
          name: sustentaree-target
          path: ./sustentaree-target/

      # Preparação do ambiente SSH
      - name: Preparar ambiente SSH
        run: |
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}
          eval "$(ssh-agent -s)"
          ssh-add $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}

      # Transferência de todos os arquivos da pasta target para a instância EC2 privada
      - name: Transferir arquivos da pasta target para a instância EC2 privada
        run: |
          scp -o StrictHostKeyChecking=no -P 2222 ./sustentaree-target/* ubuntu@localhost:/home/ubuntu/sustentare-api/

      # Reinício da aplicação na instância EC2 privada
      - name: Reiniciar aplicação na instância EC2 privada
        run: |
          ssh -o StrictHostKeyChecking=no -p 2222 ubuntu@localhost << 'EOF'
            cd /home/ubuntu/sustentare-api
            if [ -f "api.pid" ]; then
              echo "Parando aplicação existente..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi
            echo "Iniciando nova aplicação..."
            nohup java -jar -Dspring.profiles.active=prod sustentaree-0.0.1-SNAPSHOT-shaded.jar > application.log 2>&1 &
            echo $! > api.pid
          EOF
