name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualização do código
        uses: actions/checkout@v4

      - name: Desligar avisos de build
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Definindo a versão da JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
          
      - name: Build com Maven (ignorando testes)
        run: mvn -f ./sustentaree/pom.xml -X clean install -DskipTests

      - name: Build e Testes com Maven
        run: |
          mvn -f ./sustentaree/pom.xml -X clean install

      - name: Capturar Logs de Teste
        if: failure()
        run: cat sustentaree/target/surefire-reports/*.txt

      - name: Gerar artefato Github com o .jar gerado
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao
          path: sustentaree/target/*.jar

      - name: Gerar artefato Github com os arquivos .sh
        uses: actions/upload-artifact@v4
        with:
          name: scripts
          path: .github/scripts/*.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar jars
        uses: actions/download-artifact@v4
        with:
          name: aplicacao
          path: ./

      - name: Recuperar scripts
        uses: actions/download-artifact@v4
        with:
          name: scripts
          path: ./

      - name: Criar arquivo 
