name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualização do código
        uses: actions/checkout@v4

      - name: Desligar avisos de build
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Definindo a versão da JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build com Maven (ignorando testes)
        run: mvn -f ./sustentaree/pom.xml -X clean install -DskipTests

      - name: Gerar artefato Github com o .jar gerado
        uses: actions/upload-artifact@v4
        with:
          name: sustentare-api
          path: sustentaree/target  # Diretório onde o JAR será gerado

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar artefatos
        uses: actions/download-artifact@v4
        with:
          name: sustentare-api
          path: ./sustentare-api  # Diretório onde o artefato será baixado

      - name: Criar arquivo .pem para acesso à EC2 (Pública)
        run: |
          echo "${{ secrets.PUBLIC_DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}

      - name: Criar arquivo .pem para acesso à EC2 (Privada)
        run: |
          echo "${{ secrets.PRIVATE_DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}

      - name: Enviar arquivos para a instância pública
        run: |
          scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no -r ./sustentare-api/* ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }}:/home/ubuntu/sustentare-api/

      - name: Configurar túnel SSH para acessar a EC2 privada
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no -f -N -L 2222:${{ secrets.PRIVATE_EC2_IP }}:22 ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }}
          echo "Túnel SSH configurado: localhost:2222 -> ${{ secrets.PRIVATE_EC2_IP }}:22"

      - name: Conectar à instância privada e reiniciar a aplicação
        run: |
          # Verificando se o arquivo PEM existe
          echo "Verificando se o arquivo PEM existe: $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}"
          ls -l $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}

          # Verificando a conexão SSH à EC2 privada através do túnel
          echo "Testando a conexão SSH com a instância privada via túnel..."
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no -p 2222 ubuntu@localhost "echo 'Conexão bem-sucedida com a EC2 privada'"

          # Conectando à instância privada e reiniciando a aplicação
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no -p 2222 ubuntu@localhost << 'EOF'
            cd /home/ubuntu/sustentare-api
            if [ -f "api.pid" ]; then
              echo "Parando aplicação existente..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi
            echo "Iniciando nova aplicação..."
            nohup java -jar -Dspring.profiles.active=prod sustentare-api-0.0.1-SNAPSHOT-shaded.jar > application.log 2>&1 &
            echo $! > api.pid
          EOF
