name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configuração do Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Build com Maven
      - name: Build with Maven
        run: |
          mvn -f sustentaree/pom.xml clean install -DskipTests

      # Gerar artefato com o arquivo JAR
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: sustentare-api  # Nome do artefato
          path: sustentaree/target/  # Caminho correto do JAR gerado

  deploy:
    needs: build  # Esse job depende do job de build
    runs-on: ubuntu-22.04
    steps:
      # Baixar artefato gerado do job anterior
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: sustentare-api  # Nome do artefato
          path: ./sustentaree/target/  # Caminho para armazenar o artefato baixado

      # Preparação do ambiente SSH
      - name: Preparar ambiente SSH
        run: |
          chmod 400 /home/runner/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add /home/runner/.ssh/id_rsa

      # Conectar via SSH e reiniciar a aplicação
      - name: Deploy na instância EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
            cd /home/ubuntu/sustentare-api
            if [ -f "api.pid" ]; then
              echo "Parando a aplicação..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi
            echo "Iniciando a aplicação..."
            nohup java -jar -Dspring.profiles.active=prod sustentare-api-0.0.1-SNAPSHOT-shaded.jar > application.log 2>&1 &
            echo $! > api.pid
          EOF
