name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualização do código
        uses: actions/checkout@v4

      - name: Desligar avisos de build
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Definindo a versão da JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build e Testes com Maven
        run: |
          mvn -f ./sustentaree/pom.xml -X clean install

      - name: Capturar Logs de Teste
        if: failure()
        run: cat sustentaree/target/surefire-reports/*.txt

      - name: Build com Maven (ignorando testes)
        run: mvn -f ./sustentaree/pom.xml -X clean install -DskipTests

      - name: Gerar artefato Github com o .jar gerado
        uses: actions/upload-artifact@v4
        with:
          name: aplicacao
          path: sustentaree/target/*.jar

      - name: Gerar artefato Github com os arquivos .sh
        uses: actions/upload-artifact@v4
        with:
          name: scripts
          path: .github/scripts/*.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar artefatos
        uses: actions/download-artifact@v4
        with:
          name: aplicacao
          path: ./deploy-api

      - name: Recuperar scripts
        uses: actions/download-artifact@v4
        with:
          name: scripts
          path: ./deploy-api

      - name: Criar arquivo .pem para acesso à EC2
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM }}

      - name: Enviar arquivos para a instância pública
        run: |
          scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} -o StrictHostKeyChecking=no -r deploy-api/* ubuntu@${{ secrets.DEPLOY_HOST }}:/home/ubuntu/deploy-api/

      - name: Transferir arquivos da instância pública para a privada
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEPLOY_HOST }} << 'EOF'
            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} -o StrictHostKeyChecking=no -r /home/ubuntu/deploy-api/* ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api/
          EOF

      - name: Conectar à instância privada e reiniciar a aplicação
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.IP_PRIVADO_EC2 }} << 'EOF'
            # Navegar para o diretório de deploy
            cd /home/ubuntu/deploy-api

            # Parar a aplicação se estiver rodando
            if [ -f "api.pid" ]; then
              echo "Parando aplicação..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi

            # Iniciar a aplicação
            echo "Iniciando aplicação..."
            nohup java -jar -Dspring.profiles.active=prod *.jar > application.log 2>&1 &
            echo $! > api.pid
          EOF
