name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualização do código
        uses: actions/checkout@v4

      - name: Desligar avisos de build
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Definindo a versão da JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build com Maven (ignorando testes)
        run: mvn -f ./sustentaree/pom.xml -X clean install -DskipTests

      - name: Gerar artefato Github com o .jar gerado
        uses: actions/upload-artifact@v4
        with:
          name: sustantare-api  # Nome do artefato
          path: sustentaree/target/sustentaree-0.0.1-SNAPSHOT-shaded.jar  # Caminho do arquivo .jar gerado

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar artefatos
        uses: actions/download-artifact@v4
        with:
          name: sustantare-api  # Nome do artefato
          path: ./sustentaree/target  # Caminho onde o artefato será baixado

      - name: Recuperar scripts
        uses: actions/download-artifact@v4
        with:
          name: scripts
          path: ./sustentaree/scripts

      - name: Criar arquivo .pem para acesso à EC2 (Pública)
        run: |
          echo "${{ secrets.PUBLIC_DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}

      - name: Enviar arquivos para a instância pública
        run: |
          scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no -r sustentaree/target/* ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }}:/home/ubuntu/sustentaree/target/

      - name: Transferir arquivos da instância pública para a privada
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }} << 'EOF'
            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no -r /home/ubuntu/sustentaree/target/* ubuntu@${{ secrets.PRIVATE_EC2_IP }}:/home/ubuntu/sustentaree/target/
          EOF

      - name: Conectar à instância privada e reiniciar a aplicação
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
            cd /home/ubuntu/sustentaree/target
            if [ -f "api.pid" ]; then
              echo "Parando aplicação..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi
            echo "Iniciando aplicação..."
            nohup java -jar -Dspring.profiles.active=prod sustentaree-0.0.1-SNAPSHOT-shaded.jar > application.log 2>&1 &
            echo $! > api.pid
          EOF
