name: CI/CD para Spring Boot com Maven e publicação em EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Atualizar o código
        uses: actions/checkout@v4

      - name: Desligar avisos de build
        run: echo "CI=false" >> $GITHUB_ENV

      - name: Definir versão da JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build com Maven (ignorando testes)
        run: mvn -f ./sustentaree/pom.xml -X clean install -DskipTests

      - name: Verificar arquivos gerados
        run: ls -l ./sustentaree/target  # Verificando se o JAR foi gerado

      - name: Upload do artefato .jar para o GitHub
        uses: actions/upload-artifact@v4
        with:
          name: sustentare-api  # Nome do artefato
          path: ./sustentaree/target/sustentaree-0.0.1-SNAPSHOT-shaded.jar  # Caminho do arquivo gerado

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Recuperar artefatos
        uses: actions/download-artifact@v4
        with:
          name: sustentare-api  # Nome do artefato que foi enviado
          path: ./sustentare-api  # Caminho para armazenar o artefato baixado

      - name: Criar arquivo .pem para acesso à EC2 (Pública)
        run: |
          echo "${{ secrets.PUBLIC_DEPLOY_KEY }}" > $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }}

      - name: Enviar arquivos para a instância pública
        run: |
          scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no -r ./sustentare-api/* ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }}:/home/ubuntu/sustentare-api/

      - name: Transferir arquivos da instância pública para a privada
        run: |
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICA }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.PUBLIC_DEPLOY_HOST }} << 'EOF'
            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no -r /home/ubuntu/sustentare-api/* ubuntu@${{ secrets.PRIVATE_EC2_IP }}:/home/ubuntu/sustentare-api/
          EOF

      - name: Conectar à instância privada e reiniciar a aplicação
        run: |
          # Verificando se o arquivo PEM existe
          echo "Verificando se o arquivo PEM existe: $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}"
          ls -l $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }}

          # Verificando a conexão SSH à EC2
          echo "Testando a conexão SSH com a instância privada..."
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.PRIVATE_EC2_IP }} "echo 'Conexão bem-sucedida'"

          # Conectando à instância privada e reiniciando a aplicação
          ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADA }} -o StrictHostKeyChecking=no ubuntu@${{ secrets.PRIVATE_EC2_IP }} << 'EOF'
            cd /home/ubuntu/sustentare-api
            if [ -f "api.pid" ]; then
              echo "Parando aplicação..."
              kill -9 $(cat api.pid) || true
              rm api.pid
            fi
            echo "Iniciando aplicação..."
            nohup java -jar -Dspring.profiles.active=prod sustentare-api-0.0.1-SNAPSHOT-shaded.jar > 
