name: CI/CD para Spring Boot com Maven e EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build com Maven
        run: mvn clean package

      - name: Upload do JAR gerado
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

      - name: Upload dos scripts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-scripts
          path: .github/scripts/*.sh

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o JAR gerado
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./

      - name: Baixar os scripts de deploy
        uses: actions/download-artifact@v4
        with:
          name: deploy-scripts
          path: ./

      - name: Criar arquivo .pem para EC2 pública
        run: |
          echo "${{ secrets.DEPLOY_PUBLIC_KEY }}" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICO }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICO }}

      - name: Criar arquivo .pem para EC2 privada
        run: |
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" >> $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADO }}
          chmod 400 $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADO }}

      - name: Enviar arquivos para EC2 pública
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
          source: ./*.jar
          target: /home/ubuntu/deploy-api/

      - name: Enviar scripts para EC2 pública
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
          source: ./*.sh
          target: /home/ubuntu/deploy-api/

      - name: Conectar via SSH à EC2 pública e acessar a EC2 privada para deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PUBLICO }} ubuntu@${{ secrets.DEPLOY_HOST }} "
            # Passar o arquivo JAR para a EC2 privada
            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADO }} /home/ubuntu/deploy-api/*.jar ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api/
            # Passar os scripts para a EC2 privada
            scp -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADO }} /home/ubuntu/deploy-api/*.sh ubuntu@${{ secrets.IP_PRIVADO_EC2 }}:/home/ubuntu/deploy-api/
            # Reiniciar a aplicação na EC2 privada
            ssh -i $HOME/${{ secrets.NOME_ARQUIVO_PEM_PRIVADO }} ubuntu@${{ secrets.IP_PRIVADO_EC2 }} 'sh /home/ubuntu/deploy-api/api-restart.sh'
          "
